src/components/layout/Footer.js

Fixed social media links.

---

README.md

License link specified.

---

src/components/layout/Header.js
src/pages/index.js

- Fixes issue #10.
- Changed the AnchorLinks to Links in header.js.
- These links are temporary for now and will be filled in when more pages are created.
- Changed 'class' to 'className' in index.js.

Fixed links in Header navigation bar.

---

src/components/layout/Footer.js
src/pages/code-of-conduct.js

Added Code of Conduct page and linked it to the footer.

Added Code of Conduct page.

---

src/components/layout/Footer.js
src/pages/privacy-policy.js

Added privacy policy page and link to this page in the footer.

Added privacy policy page.

---

src/components/layout/Footer.js

Added copyright notice to footer.

---

gatsby-config.js
package-lock.json
package.json

I followed the instructions at: https://support.gatsbyjs.com/hc/en-us/articles/360061641114-Deploying-with-Gatsby-Cloud-Hosting

Added dependencies for deployment to Gatsby Cloud.

---

src/components/layout/Footer.js
src/components/layout/Header.js
src/pages/index.js

Added content for features and benefits.

---

README.md
gatsby-config.js
package-lock.json
package.json
postcss.config.js
src/pages/index.js
tailwind.config.js

* Resolved issue #2
* Removed codebushi theme
* Upgraded TailwindCSS to 2.2.4 
* Added PostCSS

Removed Gatsby theme

---

package-lock.json
package.json

Update to Gatsby 3.9.1

---

README.md

Improved documentation of developer workflow.

---

src/pages/index.js

Changed title and subtitle on landing page.

---

src/pages/index.js

Changed the title of home page.

---

gatsby-config.js
package-lock.json
package.json
src/components/seo.js
src/pages/about.js
src/pages/code-of-conduct.js
src/pages/index.js
src/pages/privacy-policy.js

Resolves issues #43 and #44
* Used gatsby-plugin-manifest for favicon
* Used gatsby-plugin-react-helmet for SEO and page titles/descriptions
* Added seo.js

"added favicon and page titles"

---

src/components/Button.js
src/components/layout/Footer.js
src/components/layout/Header.js
src/pages/about.js
src/pages/faq.js
src/pages/index.js
src/pages/terms-of-service.js

Resolves the following issues:
- #54
- #33
- #32
- #61

Adds new content

---

gatsby-config.js
package-lock.json
package.json
tailwind.config.js

Uses PurgeCSS to reduce size of build

---

src/pages/about.js

Fixed company name.

---

src/components/layout/Footer.js
src/pages/index.js

Moved 'Forum' link to the footer.

---

src/components/layout/Header.js

Removed 'Login' button.

---

src/components/layout/Footer.js
tailwind.config.js

Added responsive flow for footer sections.

---

src/components/layout/Footer.js

Improves #95 by consistent use of `flex` classes, rather than mixing use of `flex` and `grid`.

Uses consistent flex classes.

---

src/pages/privacy-policy.js

Fixed typo.

---

src/pages/faq.js
src/pages/index.js

Resolves #82.
* Revised content during review meeting with Craig and Jim.

Revised content in FAQ and home page.

---

src/components/layout/Header.js

Changed company name to a link to home.

---

src/components/layout/Header.js
src/pages/about.js
src/pages/communities/digital-marketing.js
src/pages/communities/machine-learning.js
src/pages/communities/ux-design.js
src/pages/index.js
src/svg/HeroImage.js

* Fixes #115.
* Added 'title' attribute to images to show text description when someone hovers over an image.
* Made 'alt' attributes more descriptive.
* Note: On iPhone, I needed to click on the image to get pop-up dialog that shows the `alt` and `title` text concatenated together.

Added 'title' attribute to images.

---

package-lock.json
package.json
src/components/layout/Footer.js

* Fixes #114.
* Uses `react-icons` package.

Added Twitter icon next to Twitter link in footer.

---

README.md

* Enhanced README.md installation instructions for developers.

Lists vscode extensions needed by developers.

---

src/pages/communities/digital-marketing.js
src/pages/communities/machine-learning.js
src/pages/communities/ux-design.js
src/pages/faq.js

Connected the alphaGoogleForm (same as on homepage) on the niche pages for:
* digital marketing
* machine learning
* ux design

Connected the alphaGoogleForm on the niche pages

---

src/pages/index.js

For discussing. would be great if you can do it (got carried away with several points). Anyway, I sent a Zoom link on email and text and will be working on other things until 4:00pm (Central) here, after which I'll be going out until 7:00pm (Central)

Rework draft of homepage.

---

src/components/SplitSection.js
src/components/layout/Footer.js
src/components/layout/Layout.js
src/pages/about.js
src/pages/communities.js
src/pages/communities/digital-marketing.js
src/pages/communities/machine-learning.js
src/pages/communities/ux-design.js
src/pages/faq.js
src/pages/index.js
tailwind.config.js

* Fixes #139.
* Improved vertical spacing across the application.
* Tested on full-size computer screen and phone.

Tuned vertical spacing on multiple pages to improve visual layout

---

src/pages/about.js
src/pages/communities.js
src/pages/faq.js

* Fixes #119.
* Moved 'Founders' section to the top.
* Reduced size of people photos.
* Revised text content for "Mission", which is now "What's in it for you?"
* Added explanation of logo and name.
Issue #119 says, "we should say what we are looking for. graphics, legal, Vue, cloud, inbound marketing in exchange for equity and could be freelancers part-time." That is not included yet in this Pull Request. Do we still want to do that?

Restructured 'About' page

---

package-lock.json
src/pages/about.js

* Added URL for Jujube Li.
* Added quotes around company name in explanation.
* Revised text of name explanation.

Adds credit for Jujube Li in the 'About' page

---

src/css/tailwind.css
src/pages/about.js
src/pages/faq.js

* Fixes #118.
* Significant rewrite from original.
* But changes are quite similar to [Craig's redesign](https://docs.google.com/document/d/1u6Ny9OBvAqP2NCSDk_wMZ01jWBD-CmFgBteu0IxFt2I/edit?usp=sharing).
* Lets text go full width of screen, even for very wide browser screen. I made this change on both FAQ and About pages.

Revised FAQ content

---

src/pages/faq.js

Removed reference to Early Access Lounge.

---

src/components/SplitSection.js
src/css/tailwind.css
src/pages/about.js
src/pages/communities.js
src/pages/communities/digital-marketing.js
src/pages/communities/machine-learning.js
src/pages/communities/ux-design.js
src/pages/index.js

* Fixes #164.
* Fixes #165.
* Changes font sizes based on screen size, so that h1, h2, h3, ... looks good on small screen and large screen with the font size adjusted depending on the screen size.
* Refactored CSS classes for consistent spacing and consistent font size across pages.
* Uses simple h1, h2, h3 whenever appropriate with additional properties as needed, e.g. `mt-0` in card headings.

Changes font size of section heading elements h1, h2, h3 based on screen size
